In [1]:
import torch

Based on the illustration below:

![hib-pairs.png](hib-pairs.png)

Link to illustration: https://excalidraw.com/#json=TgXrlm-7Eg4CGNFICqTXp,I5ByHYLDTZsDBnyNv1pVQQ

In [58]:
K = 2

y = torch.Tensor([1,2,3])

pos_anc = torch.Tensor([0,0])  # label 1, 1
pos = torch.Tensor([1,2])  # label 2, 3

In [59]:
# Mimick sample
y_sampled = y.repeat(K, 1)
y_sampled[1] += 0.1
y_sampled

tensor([[1.0000, 2.0000, 3.0000],
        [1.1000, 2.1000, 3.1000]])

In [60]:
y_k1 = y_sampled.repeat_interleave(K, dim=0)
y_k1

tensor([[1.0000, 2.0000, 3.0000],
        [1.0000, 2.0000, 3.0000],
        [1.1000, 2.1000, 3.1000],
        [1.1000, 2.1000, 3.1000]])

In [61]:
y_k2 = y_sampled.repeat(K, 1)
y_k2

tensor([[1.0000, 2.0000, 3.0000],
        [1.1000, 2.1000, 3.1000],
        [1.0000, 2.0000, 3.0000],
        [1.1000, 2.1000, 3.1000]])

In [62]:
batch_size = y.shape[0]

In [112]:
y_k1_flat = y_k1.view(K**2 * batch_size,1)
print(y_k1_flat)

print('Anchor idx: [0, 0, 3, 3, 6, 6, 9, 9]')

tensor([[1.0000],
        [2.0000],
        [3.0000],
        [1.0000],
        [2.0000],
        [3.0000],
        [1.1000],
        [2.1000],
        [3.1000],
        [1.1000],
        [2.1000],
        [3.1000]])
Anchor idx: [0, 0, 3, 3, 6, 6, 9, 9]


In [113]:
y_k2_flat = y_k2.view(K**2 * batch_size,1)
print(y_k2_flat)

print('Positive idx: [1, 2, 4, 5, 7, 8, 10, 11]')

tensor([[1.0000],
        [2.0000],
        [3.0000],
        [1.1000],
        [2.1000],
        [3.1000],
        [1.0000],
        [2.0000],
        [3.0000],
        [1.1000],
        [2.1000],
        [3.1000]])
Positive idx: [1, 2, 4, 5, 7, 8, 10, 11]


In [109]:
batch_step = torch.arange(0, K**2).repeat_interleave(pos.shape[0]) * batch_size
batch_step

tensor([0, 0, 3, 3, 6, 6, 9, 9])

In [110]:
pos.repeat(K**2) + batch_step

tensor([ 1.,  2.,  4.,  5.,  7.,  8., 10., 11.])

In [111]:
pos_anc.repeat(K**2) + batch_step

tensor([0., 0., 3., 3., 6., 6., 9., 9.])